### ISSUE TITLE
Implement Lighthouse in CI Pipeline

### ISSUE THREAD

**Issue by Hakim-Kay** [Hakim-Kay/wedding-app#18]
### User Story

As a developer,
I want automated PWA audits in our CI pipeline
so that we can ensure PWA best practices are maintained with each build.

---
### In Scope

- Integrate Lighthouse audits into the CI pipeline
- Configure audit thresholds for pass/fail criteria
- Set up reporting mechanism for audit results

---
> Example
```yaml
# In .github/workflows/pwa-audit.yml
- name: Run Lighthouse CI
  uses: treosh/lighthouse-ci-action@v9
  with:
    configPath: './lighthouserc.json'
    uploadArtifacts: true
```
---
### Acceptance Criteria:

- [ ] Lighthouse audits run automatically on each PR
- [ ] Failed audits block merging
- [ ] Report generated and accessible for each audit
- [ ] Developers receive notifications for failed audits
