### ISSUE TITLE
Automate Database Migrations in CI/CD Pipeline

### ISSUE THREAD

**Issue by Hakim-Kay** [Hakim-Kay/wedding-app#21]
### User Story

As a database administrator,
I want automated database migrations in our CI/CD pipeline
so that database schema changes are consistently applied across all environments.

---
### In Scope

- Implement automated migration scripts
- Integrate migration process into CI/CD pipeline
- Develop rollback mechanism for failed migrations

---
> Example
```yaml
# In .github/workflows/deploy.yml
- name: Run Database Migrations
  run: |
    npx prisma migrate deploy
  env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
```
---
### Acceptance Criteria:

- [ ] Migrations run automatically during deployment
- [ ] Rollback mechanism in place for failed migrations
- [ ] Developers can easily create and test migrations locally
- [ ] Migration history is tracked and easily viewable
