### ISSUE TITLE
Integrate Security Scanning Tools

### ISSUE THREAD

**Issue by Hakim-Kay** [Hakim-Kay/wedding-app#22]
### User Story

As a security engineer,
I want automated security scans in our CI pipeline
so that we can identify and address vulnerabilities early in the development process.

---
### In Scope

- Integrate OWASP ZAP for dynamic application security testing
- Set up Snyk for dependency vulnerability scanning
- Configure scans to run on each PR and regularly on the main branch

---
> Example
```yaml
# In .github/workflows/security-scan.yml
- name: ZAP Scan
  uses: zaproxy/action-full-scan@v0.4.0
  with:
    target: 'https://staging.ourwedding.com'
```
---
### Acceptance Criteria:

- [ ] Security scans run on each PR
- [ ] Failed scans block merging
- [ ] Regular scans scheduled for the main branch
- [ ] Scan reports are generated and accessible to the security team
