### ISSUE TITLE
Implement Load Testing in CI Pipeline

### ISSUE THREAD

**Issue by Hakim-Kay** [Hakim-Kay/wedding-app#24]
### User Story

As a QA engineer,
I want automated load testing in our CI pipeline
so that we can ensure the application performs well under expected traffic.

---
### In Scope

- Define and implement load test scenarios
- Integrate load testing tool into CI pipeline
- Set up performance benchmarks and reporting

---
> Example
```yaml
# In .github/workflows/load-test.yml
- name: Run k6 Load Test
  uses: grafana/k6-action@v0.2.0
  with:
    filename: loadtests/main.js
```
---
### Acceptance Criteria:

- [ ] Load tests defined and automated in CI pipeline
- [ ] Tests run on staging environment before production deployment
- [ ] Performance benchmarks established and monitored
- [ ] Load test reports generated and accessible to the team
